window.ARTICLE_DATA = [
  {
    "id": "01",
    "title": "js手写深拷贝",
    "category": "JavaScript",
    "summary": "手写一个支持对象、数组、Map、Set、Promise、正则和日期的深拷贝方法。",
    "source": "article/01.js手写深拷贝.txt",
    "content": "最近项目需要用到深拷贝，不想去单独安装一个库，就自己手写了。\r\n\r\n支持基本数据，null，undefined，布尔，数字，字符串。支持Object类型的 Map，Set，Promise，正则，日期，函数，数组，Object 类型数据。另外也支持里面数据内有属性是引用的。\r\n\r\n```js\r\nlet _toString = Object.prototype.toString\r\n\r\nfunction isPrimitive(val) {\r\n    if (val === null) {\r\n        return true\r\n    }\r\n    return !(typeof val === 'object' || typeof val === 'function')\r\n}\r\n\r\nfunction getRegExpFlags(re) {\r\n    let flags = ''\r\n    if (re.global) flags += 'g'\r\n    if (re.ignoreCase) flags += 'i'\r\n    if (re.multiline) flags += 'm'\r\n    return flags;\r\n}\r\n\r\nfunction deepClone(obj) {\r\n    if (isPrimitive(obj) || typeof obj == 'function') {\r\n        return obj\r\n    }\r\n\r\n    let everyVal = []\r\n    let result = undefined\r\n\r\n    if (obj instanceof Map) {\r\n        result = new Map()\r\n    } else if (obj instanceof Set) {\r\n        result = new Set()\r\n    } else if (obj instanceof Promise) {\r\n        result = new Promise(function (resolve, reject) {\r\n            obj.then(function (value) {\r\n                resolve(deepClone(value))\r\n            }, function (err) {\r\n                reject(deepClone(err))\r\n            })\r\n        })\r\n    } else if (Array.isArray(obj)) {\r\n        result = []\r\n    } else if (_toString.call(obj) === '[object RegExp]') {\r\n        result = new RegExp(obj.source, getRegExpFlags(obj))\r\n        if (obj.lastIndex) result.lastIndex = obj.lastIndex\r\n    } else if (_toString.call(obj) === '[object Date]') {\r\n        result = new Date(obj.getTime())\r\n    } else if (obj instanceof Error) {\r\n        result = Object.create(obj)\r\n    } else {\r\n        let proto = Object.getPrototypeOf(obj)\r\n        result = Object.create(proto)\r\n    }\r\n\r\n    let index = everyVal.indexOf(obj)\r\n    if (index !== -1) {\r\n        return everyVal[index]\r\n    }\r\n    everyVal.push(obj)\r\n\r\n    for (let k in obj) {\r\n        result[k] = deepClone(obj[k])\r\n    }\r\n    return result\r\n}\r\n```"
  },
  {
    "id": "02",
    "title": "在 vue 中手写虚拟列表",
    "category": "Vue",
    "summary": "通过固定容器高度和动态渲染可视区域数据，降低长列表 DOM 压力。",
    "source": "article/02.在 vue 中手写虚拟列表.txt",
    "content": "后端一次返回数据过多，或者向下滚动过程会叠加渲染产生的新数据，会导致页面的 dom 元素越来越多，慢慢也就会变的有卡顿的感觉，于是想到使用虚拟列表。只渲染用户看到的数据，操作过程中不停更新用户看到的数据。\r\n\r\n# 1.定义变量\r\n```\r\ndata() {\r\n return {\r\n  fleetAll: [],  //  列表全部数据\r\n  fleetShowList: [],  //  列表全部数据中需要的渲染数据\r\n  fleetScrollTop: 0,  //  父级 y 轴 scroll 滚动距离\r\n  fleetBoxHeight: 12*32,  //  父级元素的高度  默认渲染12条\r\n }\r\n},\r\n```\r\n\r\n# 2.template 模板\r\n```\r\n<div class=\"h300 pr ova\" @scroll=\"scrollFleet\">\r\n <div :style=\"'height: '+fleetBoxHeight+'px;'\">\r\n  <div class=\"lin32 hover pa l0\" :style=\"'top: '+item.top+'px;'\" v-for=\"(item, keys) in fleetShowList\" :key=\"item.id\">{{ item.name }}</div>\r\n </div>\r\n</div>\r\n```\r\n\r\n# 3. 函数处理\r\n```\r\n//  初始化数据\r\ninitData() {\r\n let fleetList = []\r\n for (let i=1;i<200;i++) {\r\n  fleetList.push({id: String(i), name: '车队'+String(i).padStart(3, '0')+'车队'})\r\n }\r\n this.fleetBoxHeight = fleetList.length*32\r\n this.fleetAll = fleetList\r\n},\r\n//  scroll 事件处理\r\nscrollFleet(e) {\r\n this.fleetScrollTop = e.target.scrollTop\r\n this.handleFleetShowList()\r\n},\r\n//  scroll 过程中渲染数据处理\r\nhandleFleetShowList() {\r\n let oldStartIdx = this.startIdx\r\n //  防止滚动到最下面时如果滚动距离超过最大可滚动距离，会出现最后一个元素定位超出，导致一直可以滚动\r\n if (this.fleetBoxHeight>300 && this.fleetScrollTop>(this.fleetBoxHeight-300)) {\r\n  this.fleetScrollTop = (this.fleetBoxHeight-300)\r\n }\r\n this.startIdx = Math.floor(this.fleetScrollTop / 32)\r\n let fleet12 = []\r\n let fl = fleet12.length\r\n while (fl<12 && (this.startIdx+fl)<this.fleetAll.length) {\r\n  let fitem = this.fleetAll[this.startIdx+fl]\r\n  if (oldStartIdx != this.startIdx) {\r\n   fitem.top = this.fleetScrollTop+(fl*32)\r\n  }\r\n  //  向上滚动到第一条数据时，可能存在第一条数据有定位距离，如果接着向上滚动，则清空第一条定位距离\r\n  if (oldStartIdx == 0 && this.startIdx == 0) {\r\n   fitem.top = fl*32\r\n  }\r\n  fleet12.push(fitem)\r\n  fl = fleet12.length\r\n }\r\n this.fleetShowList = fleet12\r\n},\r\n```\r\n\r\n# 4.虚拟列表效果\r\n\r\n![虚拟列表.gif](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/48d1ae349d814e879badced9a4c4e536~tplv-k3u1fbpfcp-watermark.image?)"
  },
  {
    "id": "03",
    "title": "手写简易日期格式化和日期解析",
    "category": "JavaScript",
    "summary": "实现常用日期格式化与日期字符串解析，覆盖年月日时分秒格式。",
    "source": "article/03.手写简易日期格式化和日期解析.txt",
    "content": "## 1.日期格式化\r\n```js\r\nfunction formatDate(date, fmt) {\r\n  if (!(date instanceof Date)) {\r\n    date = new Date()\r\n  }\r\n  if (!fmt) {\r\n    fmt = 'yyyy-MM-dd HH:mm:ss'\r\n  }\r\n  let result = fmt.replace(/h/g, 'H')\r\n  let dateObj = {}\r\n  dateObj['y'] = date.getFullYear()\r\n  dateObj['M'] = date.getMonth()+1\r\n  dateObj['d'] = date.getDate()\r\n  dateObj['H'] = date.getHours()\r\n  if (fmt.indexOf('h')>0 && dateObj['H']>12) {\r\n    dateObj['H'] -= 12\r\n  }\r\n  dateObj['m'] = date.getMinutes()\r\n  dateObj['s'] = date.getSeconds()\r\n\r\n  for (let dateKey in dateObj) {\r\n    result = result.replace(new RegExp(dateKey+'+', 'g'), m => {\r\n      let dateVal = dateObj[dateKey] + ''\r\n      if (dateVal.length < 2) {\r\n        dateVal = dateVal.padStart(2, '0')\r\n      }\r\n      if (dateVal.length <= m.length) {\r\n        return dateVal\r\n      }\r\n      return dateVal.slice(dateVal.length-m.length)\r\n    })\r\n  }\r\n\r\n  return result\r\n}\r\n\r\n```\r\n\r\n## 2.日期解析\r\n```js\r\nfunction parseDate(str, fmt) {\r\n  fmt = fmt || 'yyyy-MM-dd HH:mm:ss'\r\n  fmt = fmt.replace(/h/g, 'H')\r\n  let result = ''\r\n  let obj = {y: 0, M: 1, d: 0, H: 0, m: 0, s: 0}\r\n  for (let dateKey in obj) {\r\n    let resArr = new RegExp(dateKey+'+', 'g').exec(fmt)\r\n    obj[dateKey] = Number(str.slice(resArr.index, resArr.index+resArr[0].length))\r\n  }\r\n\r\n  // 月份是从0开始的，所以要减去1\r\n  obj.M--\r\n  let date = new Date(obj.y, obj.M, obj.d, obj.H, obj.m, obj.s)\r\n\r\n  return date;\r\n}\r\n\r\n```\r\n\r\n## 3.测试\r\n```js\r\nconsole.log(formatDate(new Date(), 'yy-MM-dd HH:mm:ss'))\r\nconsole.log(parseDate('2022-11-25 10:25:36', 'yyyy-MM-dd HH:mm:ss'))\r\n```"
  },
  {
    "id": "04",
    "title": "如何把本地项目提交到 github",
    "category": "工程化",
    "summary": "记录 SSH Key 配置、GitHub 仓库创建和本地项目提交的完整流程。",
    "source": "article/04.如何把本地项目提交到 github.txt",
    "content": "# 1. 在本地创建 ssh key 文件，与 github 上自己的账号关联\r\n如果没有在本地创建 ssh key 与 github 关联，自己在提交仓库的时候就会出现\r\n\r\nPermission denied (publickey). \r\n\r\nfatal: Could not read from remote repository.\r\n\r\nPlease make sure you have the correct access rights and the repository exists.\r\n\r\n![image.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7b196bf7500543c1973cbf1136d156dd~tplv-k3u1fbpfcp-watermark.image?)\r\n\r\n出现这个错误的原因是：`你在本地或者服务器上面没有生成ssh key导致的。`\r\n\r\n## 1.1 检查 .ssh 目录\r\n进入 C:\\Users\\administrator\\.ssh 目录，如果没有 id_rsa 和 id_rsa.pub 文件，就是没有ssh key ，需要创建。\r\n\r\n## 1.2 创建 ssh key \r\n在ternimal下输入命令：\r\n```sh\r\nssh-keygen -t rsa -C \"youremail@example.com\"\r\n```\r\nyouremail@example.com改为自己的邮箱即可，途中会让你输入密码啥的，不需要管，一路回车即可，会生成你的ssh key。（如果重新生成的话会覆盖之前的ssh key。）\r\n\r\n![image.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/55cdde474d5d4c53aaf7aa5d3da46bad~tplv-k3u1fbpfcp-watermark.image?)\r\n\r\n## 1.3 ssh -v git@github.com\r\n在ternimal下执行命令：ssh -v git@github.com最后两句会出现：\r\n\r\n No more authentication methods to try.  \r\n\r\n Permission denied (publickey).\r\n \r\n \r\n ## 1.4 ssh-agent -s\r\n\r\n 在ternimal下执行命令：ssh-agent -s\r\n\r\n会提示类似的信息：\r\n\r\n SSH_AUTH_SOCK=/tmp/ssh-GTpABX1a05qH/agent.404; export SSH_AUTH_SOCK;  \r\n\r\n SSH_AGENT_PID=13144; export SSH_AGENT_PID;  \r\n\r\n echo Agent pid 13144;\r\n \r\n ## 1.5 ssh-add ~/.ssh/id_rsa\r\n在ternimal下执行命令：ssh-add ~/.ssh/id_rsa\r\n\r\n这时候应该会提示： Identity added: ...（这里是一些ssh key文件路径的信息）\r\n\r\n（注意）如果出现错误提示：Could not open a connection to your authentication agent.\r\n\r\n请执行命令：`eval ssh-agent -s`后继续执行命令 `ssh-add ~/.ssh/id_rsa` ，这时候一般没问题啦。\r\n\r\n## 1.6 打开 id_rsa.pub\r\n打开你刚刚生成的 id_rsa.pub ，将里面的内容复制，进入你的github账号，在settings下，SSH and GPG keys下new SSH key，title 随便取一个名字，然后将 id_rsa.pub 里的内容复制到Key中，完成后Add SSH Key。\r\n\r\n![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/569beba42bf94b29939581dce878a36b~tplv-k3u1fbpfcp-watermark.image?)\r\n\r\n## 1.7 验证 Key\r\n在ternimal下输入命令：ssh -T git@github.com\r\n\r\n提示：Hi xxx! You've successfully authenticated, but GitHub does not provide shell  access.\r\n \r\n关联 ssh key 的操作就成功完成了。\r\n\r\n# 2. 把本地项目提交到 github 仓库\r\n\r\n## 2.1 在 github 上新建仓库\r\n\r\n![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b95fbc60fceb48f9b2097fdb82cfc483~tplv-k3u1fbpfcp-watermark.image?)\r\n\r\n## 2.2 设置本地项目的远程仓库\r\n\r\n![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/749029b3a6df43d3837f702d4f7ee47c~tplv-k3u1fbpfcp-watermark.image?)\r\n\r\n## 2.3 提交到远程仓库\r\n第一次提交到远程仓库，如果是 main 分支可能需要 force push 。\r\n\r\n![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3e58a5a1ef5f424780abfa7cf3c3bd58~tplv-k3u1fbpfcp-watermark.image?)"
  },
  {
    "id": "05",
    "title": "使用 rem 适配大屏",
    "category": "可视化",
    "summary": "使用 rem 思路适配 1920 与 4K 大屏，并处理 ECharts 尺寸缩放。",
    "source": "article/05.使用 rem 适配大屏.txt",
    "content": "比如项目使用的只说是大屏展示，设计出的是 1920*1080px 的图，开发的时候也是按照设计图开发的。后来上线的时候，客户的设备是 4K 大屏，上线的系统内容就会比较小，希望能同比例展示。\r\n\r\n经过研究，决定使用 rem 适配。\r\n\r\n## 1.在 app.vue 中写入 rem 代表的像素值。\r\n```js\r\n//  处理宽高,适配 3840 的宽度，如果没有 3840 的宽度，则使用等比缩放\r\nonMounted(() => {\r\n  resizeScale();\r\n  window.addEventListener('resize', () => {\r\n    resizeScale();\r\n  });\r\n});\r\n\r\nconst resizeScale = () => {\r\n  const baseWidth = 3840; // 设计稿宽度（px）\r\n  const baseFontSize = 1; // 基准：1rem = 1px => 1920px = 1920rem\r\n\r\n  const scale = document.documentElement.clientWidth / baseWidth;\r\n  // 可选：限制缩放范围（如最小 0.3，最大 1.2）\r\n  const clampedScale = Math.min(Math.max(scale, 0.3), 1.2);\r\n  document.documentElement.style.fontSize = clampedScale * baseFontSize + 'px';\r\n\r\n};\r\n```\r\n\r\n\r\n## 2.echarts 配置项使用函数处理\r\n```js\r\nconst toPxWidth = width => {\r\n  let baseWidth = 3840;\r\n  const scale = document.documentElement.clientWidth / baseWidth;\r\n  return scale * width;\r\n};\r\n\r\nlet echartsOption = {\r\n    legend: {\r\n      show: false,\r\n    },\r\n    grid: {\r\n      width: () => toPxWidth(560),\r\n      height: () => toPxWidth(600),\r\n      top: () => toPxWidth(10),\r\n      left: () => toPxWidth(10),\r\n      right: () => toPxWidth(10),\r\n      bottom: () => toPxWidth(10),\r\n      containLabel: true,\r\n    },\r\n    tooltip: {\r\n      show: true,\r\n      trigger: 'axis',\r\n      backgroundColor: 'rgba(0, 44, 101, 0.75)',\r\n      borderColor: 'rgba(147, 199, 255, 0.75)',\r\n      textStyle: {\r\n        color: '#FFFFFF',\r\n        fontSize: () => toPxWidth(18),\r\n      }\r\n    },\r\n\t...\r\n}\r\n```"
  },
  {
    "id": "06",
    "title": "现场地图不显示问题排查",
    "category": "问题排查",
    "summary": "复盘百度地图线上局部瓦片空白问题的定位过程与临时解决方案。",
    "source": "article/06.现场地图不显示问题排查.txt",
    "content": "项目使用的是百度地图，一直运行良好，没有问题，交给客户时候，上线一年多都没有问题。\r\n\r\n突然有一天，项目打开的页面上，地图有几块是空白的白块，其他地方能正常加载，地图正常是被分割很多瓦片的，放大或缩小就是加载不同层级的瓦片，然后拼成一张地图。\r\n\r\n既然其他能加载，只有一部分加载失败，说明配置，使用方式是没有问题的，初步判断是网络问题，或者部分有权限问题。\r\n\r\n经过本地运行，发现缩放都是没有问题的，线上和本地也是用的同一个 ak, 说明网络和权限是没问题，是线上的问题，那就是环境问题。\r\n\r\n查看百度地图官网，发现有商业使用说明，于是认为是 ak 被线上 ip 多次使用, 被判定为商业，从而被限制。\r\n\r\n于是，重新申请新的 ak，问题才算临时解决。最终重新设计需求，改为文字展示地址，迭代开发才算最终解决。"
  }
];
